language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install -v
  - pip install tox-travis
script:
  - tox
deploy:
  provider: script
  script:
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
    - poetry publish --build
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
